name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t manvendra1097/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true manvendra1097/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.ACCESS_KEY }}
          aws_secret_key: ${{ secrets.SECRET_ACCESS_KEY }}
          application_name: webapp
          environment_name: Webapp-env
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
